### PR TITLE
Code coverage with PhpUnit + Folder for Transformer class

### PR DESCRIPTION
**Pull request by joel-depiltech**

### CODE REVIEW

**Comment by harunyasar** [comment]
I will check the namespaces.

**Comment by harunyasar** [comment]
@joel-depiltech please update your master branch and pr with changes ;) I fixed the namespace problem.

**Comment by harunyasar** [comment]
Is that ok? @joel-depiltech

**Comment by joel-depiltech** [comment]
Hello Harun,

No It still does not work for me.
Let me try something and I will send you a pull request.

PS: I will answer to your other message soon

Regards,
Joël

**Comment by joel-depiltech** [comment]
This is the way I can use this package as a dependency and I added a new method.
Please can you accept my pull request ?

**Pull request merged**
